version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/foro_hub
      DB_USERNAME: root
      DB_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: foro_hub
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
